default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [ pep8-naming ]
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.910'  # Use the sha / tag you want to point at
#    hooks:
#      - id: mypy
#        additional_dependencies: [ types-click, types-toml ]
#        args: [ --no-strict-optional ]
